on:
  push:
    branches:
      - main

jobs:
  rm_old_images:
    runs-on: ubuntu-latest
    name: A job to remove images
    steps:
      - name: Checking out our code
        uses: actions/checkout@master
      - name: Remove the images
        uses: stevemar/image-deleter@v1.0.1
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: $
          commit-message: Remove unused images
          title: '[Automated PR] Remove unused images'
          body: |
            Found a few images that can be removed
            [1]: https://github.com/stevemar/image-deleter
      - name: Check outputs
        run: |
          echo "Pull Request Number - $"
          echo "Pull Request URL - $"
